// Generated by scripts/villager-faces.py from the villagers' alpha. Do not edit by hand.
import type { VillagerId, VillagerPose } from "@/constants/villagers";

/** The head-and-shoulders square in a villager's art, as fractions of its width and height. */
export type FaceFrame = { x: number; y: number; side: number };

export const VILLAGER_FACES: Record<VillagerId, Record<VillagerPose, FaceFrame>> = {
  champion: {
    cheer: { x: 0.2881, y: 0.2581, side: 0.48 },
    concern: { x: 0.3058, y: 0.0393, side: 0.48 },
    salute: { x: 0.2527, y: 0.0065, side: 0.48 },
    talk: { x: 0.2631, y: 0.0159, side: 0.48 },
    urge: { x: 0.2881, y: 0.0659, side: 0.48 },
  },
  farmer: {
    cheer: { x: 0.2277, y: 0.1956, side: 0.48 },
    concern: { x: 0.2996, y: 0.0331, side: 0.48 },
    salute: { x: 0.2538, y: 0.0659, side: 0.48 },
    talk: { x: 0.2496, y: 0.069, side: 0.48 },
    urge: { x: 0.3975, y: 0.0972, side: 0.48 },
  },
  herbalist: {
    cheer: { x: 0.2371, y: 0.1831, side: 0.48 },
    concern: { x: 0.2673, y: 0.0472, side: 0.48 },
    salute: { x: 0.2631, y: 0.0237, side: 0.48 },
    talk: { x: 0.2746, y: 0.0222, side: 0.48 },
    urge: { x: 0.3017, y: 0.0503, side: 0.48 },
  },
  minstrel: {
    cheer: { x: 0.286, y: 0.1128, side: 0.48 },
    concern: { x: 0.2173, y: 0.0643, side: 0.48 },
    salute: { x: 0.2631, y: 0.0378, side: 0.48 },
    talk: { x: 0.2506, y: 0.03, side: 0.48 },
    urge: { x: 0.1256, y: 0.0425, side: 0.48 },
  },
  sage: {
    cheer: { x: 0.2444, y: 0.23, side: 0.48 },
    concern: { x: 0.2715, y: 0.0722, side: 0.48 },
    salute: { x: 0.26, y: 0.0237, side: 0.48 },
    talk: { x: 0.2569, y: 0.0315, side: 0.48 },
    urge: { x: 0.2777, y: 0.0503, side: 0.48 },
  },
  smith: {
    cheer: { x: 0.26, y: 0.1862, side: 0.48 },
    concern: { x: 0.2288, y: 0.0331, side: 0.48 },
    salute: { x: 0.2506, y: 0.0315, side: 0.48 },
    talk: { x: 0.2694, y: 0.0331, side: 0.48 },
    urge: { x: 0.2621, y: 0.0034, side: 0.48 },
  },
  watcher: {
    cheer: { x: 0.2308, y: 0.2722, side: 0.48 },
    concern: { x: 0.2787, y: 0.0878, side: 0.48 },
    salute: { x: 0.2663, y: 0.0065, side: 0.48 },
    talk: { x: 0.2621, y: 0.0456, side: 0.48 },
    urge: { x: 0.2663, y: 0.0331, side: 0.48 },
  },
};
