// This file is auto-generated by scripts/generate-game-icons.js.
// Do not edit by hand. Update src/icons/gameIcons.allowlist.json and re-run the generator.

import type { ImageSourcePropType } from "react-native";

export const GAME_ICON_SOURCES = {
  "lorc/anvil": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/anvil.svg"),
  "lorc/archery-target": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/archery-target.svg"),
  "lorc/campfire": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/campfire.svg"),
  "lorc/cash": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/cash.svg"),
  "lorc/castle": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/castle.svg"),
  "lorc/checked-shield": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/checked-shield.svg"),
  "lorc/crossed-swords": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/crossed-swords.svg"),
  "lorc/crown-coin": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/crown-coin.svg"),
  "lorc/crowned-skull": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/crowned-skull.svg"),
  "lorc/cycle": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/cycle.svg"),
  "lorc/drop": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/drop.svg"),
  "lorc/feather": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/feather.svg"),
  "lorc/fire-silhouette": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/fire-silhouette.svg"),
  "lorc/flying-flag": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/flying-flag.svg"),
  "lorc/lightning-branches": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/lightning-branches.svg"),
  "lorc/locked-chest": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/locked-chest.svg"),
  "lorc/open-book": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/open-book.svg"),
  "lorc/scroll-unfurled": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/scroll-unfurled.svg"),
  "lorc/star-prominences": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/star-prominences.svg"),
  "lorc/stone-block": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/stone-block.svg"),
  "lorc/stopwatch": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/stopwatch.svg"),
  "lorc/sundial": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/sundial.svg"),
  "lorc/treasure-map": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/treasure-map.svg"),
  "lorc/trophy": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/trophy.svg"),
  "lorc/unlocking": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/unlocking.svg"),
  "lorc/wheat": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/wheat.svg"),
  "lorc/wood-axe": require("./../../assets/game-icons.net.svg-foreground-white/icons/ffffff/transparent/1x1/lorc/wood-axe.svg"),
} as const satisfies Record<string, ImageSourcePropType>;

export type GameIconName = keyof typeof GAME_ICON_SOURCES;

export const GAME_ICON_NAMES = Object.keys(GAME_ICON_SOURCES) as GameIconName[];

export function isGameIconName(name: string): name is GameIconName {
  return name in GAME_ICON_SOURCES;
}

export function getGameIconSource(name: GameIconName): ImageSourcePropType {
  return GAME_ICON_SOURCES[name];
}
