const { withGradleProperties } = require("expo/config-plugins");

/**
 * Two gradle.properties flips that only make the download smaller.
 *
 * `expo.useLegacyPackaging=true` puts the native libraries back under deflate. Expo's default
 * stores them uncompressed and page-aligned so Android can map them straight out of the APK,
 * which is the right trade for a Play install — Play strips the compression itself and serves
 * per-device splits. It is the wrong trade here: this app is downloaded as a whole APK from
 * F-Droid and from GitHub Releases, where those 25 `.so` were 23.6 MiB of a 67.1 MiB v1.13.0 and
 * deflate to 8.0 MiB. The cost is real and paid once: Android extracts them at install time, so
 * the device carries roughly 8 MiB more and the install takes a moment longer.
 *
 * `expo.gif.enabled=false` drops Fresco's GIF decoders (`libgifimage`, `libanimation-decoder-gif`,
 * 0.56 MiB). Fresco only backs `<Image>` from react-native; every image in this app is drawn by
 * expo-image, which decodes through Glide, and there is not one GIF in `assets/`. Turn it back on
 * the day a GIF appears — the symptom would be a blank image, not a build error.
 *
 * WebP is deliberately left enabled: the same reasoning would apply, but 295 of the app's assets
 * are WebP and a wrong call there is 295 blank images.
 *
 * `android/` is committed only for F-Droid's subdir check and regenerated by prebuild, so this
 * has to be a plugin rather than an edit; same reason as `withAndroidGradleMemory`.
 */
const PROPERTIES = {
  "expo.useLegacyPackaging": "true",
  "expo.gif.enabled": "false",
};

module.exports = function withAndroidSmallerApk(config) {
  return withGradleProperties(config, (cfg) => {
    for (const [key, value] of Object.entries(PROPERTIES)) {
      const existing = cfg.modResults.find((item) => item.type === "property" && item.key === key);

      if (!existing) {
        throw new Error(`withAndroidSmallerApk: ${key} is not in the generated gradle.properties`);
      }
      existing.value = value;
    }
    return cfg;
  });
};
