const { withAppBuildGradle } = require("expo/config-plugins");

/**
 * Give debug builds their own application id, so a dev build can sit next to the installed
 * release instead of replacing it.
 *
 * Without this, both variants are `com.guiforge.bati`. The release is signed with
 * `bati-release.keystore` and a debug build with Android's debug key, so Android refuses the
 * install outright (`INSTALL_FAILED_UPDATE_INCOMPATIBLE`) and the only way forward is
 * `adb uninstall com.guiforge.bati` — which takes the SQLite database, and therefore the
 * hero, the streak and the whole journal, with it. Testing a UI change should not cost a
 * training history.
 *
 * With the suffix, `npx expo run:android` installs `com.guiforge.bati.dev` as a second app with
 * its own sandbox: its own database (empty — expect to redo onboarding), its own notification
 * channels, its own widget. The release install is never touched.
 *
 * **Only the debug variant is suffixed.** The release id must stay exactly `com.guiforge.bati`
 * or every already-installed copy — GitHub Releases, the F-Droid repo — stops seeing updates as
 * updates. That is the one thing this plugin must never break.
 *
 * Both apps register the `bati://` scheme, so Android will ask which one to open for a deep
 * link while the dev build is installed.
 *
 * `android/` is gitignored and regenerated by prebuild, so this has to be a plugin rather than an
 * edit; same reason as `withAndroidReleaseSigning` and `withAndroidLintExtraTranslation`.
 */
const DEBUG_BLOCK = `        debug {
            signingConfig signingConfigs.debug
        }
`;

const SUFFIXED_DEBUG_BLOCK = `        debug {
            signingConfig signingConfigs.debug
            // See plugins/withAndroidDebugAppId.js — keeps the release install alive.
            applicationIdSuffix '.dev'
        }
`;

module.exports = function withAndroidDebugAppId(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withAndroidDebugAppId: expected a groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    if (cfg.modResults.contents.includes("applicationIdSuffix")) {
      return cfg;
    }
    if (!cfg.modResults.contents.includes(DEBUG_BLOCK)) {
      throw new Error("withAndroidDebugAppId: debug build type is not the shape expected");
    }

    cfg.modResults.contents = cfg.modResults.contents.replace(DEBUG_BLOCK, SUFFIXED_DEBUG_BLOCK);
    return cfg;
  });
};
