const fs = require("node:fs");
const path = require("node:path");
const { withDangerousMod } = require("@expo/config-plugins");

/**
 * Give the debug build a different launcher icon background, so it's visually distinguishable
 * from the release app on the home screen — both are installed side by side (see
 * `withAndroidDebugAppId`) and share the same foreground glyph.
 *
 * The adaptive icon background is `@color/iconBackground` (`android/app/src/main/res/values/
 * colors.xml`, generated by prebuild from `app.json`'s `android.adaptiveIcon.backgroundColor`).
 * Gradle resource merging lets `src/debug/res` override a `src/main/res` value for the debug
 * variant only, so no new icon image is needed — just a colour override in the debug source set.
 * `android/` is gitignored and regenerated by prebuild, hence a plugin rather than a committed file.
 */
const DEBUG_COLORS_XML = `<resources>
  <!-- See plugins/withAndroidDebugIcon.js — marks the dev build's launcher icon. -->
  <color name="iconBackground">#F59E0B</color>
</resources>
`;

module.exports = function withAndroidDebugIcon(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const valuesDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "debug",
        "res",
        "values",
      );
      fs.mkdirSync(valuesDir, { recursive: true });
      fs.writeFileSync(path.join(valuesDir, "colors.xml"), DEBUG_COLORS_XML);
      return cfg;
    },
  ]);
};
