const fs = require("node:fs");
const path = require("node:path");
const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins");

/**
 * Plain HTTP, for this phone only.
 *
 * Device sync speaks WebDAV to whatever server the hero names (src/cloudSync.ts), and one of those
 * servers can be on the phone itself: Round Sync serves any rclone remote over WebDAV on
 * `127.0.0.1`, which is how Proton Drive and Google Drive reach Bati without a line of their own.
 * That server speaks plain HTTP, and a release build refuses cleartext by default.
 *
 * So cleartext is allowed for `localhost` and `127.0.0.1` and nothing else: traffic that never
 * leaves the device, carrying files already sealed with the backup key. Every other host stays
 * HTTPS-only, as before; the base config says so explicitly rather than by default.
 *
 * Debug builds get a second copy that allows cleartext everywhere, because the dev client loads
 * its bundle from Metro over plain HTTP on the LAN, and a network security config overrides the
 * `usesCleartextTraffic` the debug manifest sets for that.
 *
 * `__tests__/android-network-security.test.ts` reads the committed output.
 */
const RELEASE = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidNetworkSecurity.js. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="false" />
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">127.0.0.1</domain>
  </domain-config>
</network-security-config>
`;

const DEBUG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidNetworkSecurity.js. Debug only: Metro serves over HTTP. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

const FILE = "bati_network_security.xml";

module.exports = function withAndroidNetworkSecurity(config) {
  const withFiles = withDangerousMod(config, [
    "android",
    (cfg) => {
      const app = path.join(cfg.modRequest.platformProjectRoot, "app/src");
      for (const [variant, contents] of [
        ["main", RELEASE],
        ["debug", DEBUG],
      ]) {
        const dir = path.join(app, variant, "res/xml");
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, FILE), contents);
      }
      return cfg;
    },
  ]);

  return withAndroidManifest(withFiles, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) throw new Error("withAndroidNetworkSecurity: no <application> in the manifest");
    app.$["android:networkSecurityConfig"] = "@xml/bati_network_security";
    return cfg;
  });
};
