const { withAppBuildGradle } = require("expo/config-plugins");

/**
 * Give locally built apps their own application id, so a build under test can sit next to the
 * installed release instead of replacing it.
 *
 * Without this, both variants are `com.guiforge.bati`. The release is signed with
 * `bati-release.keystore` and a debug build with Android's debug key, so Android refuses the
 * install outright (`INSTALL_FAILED_UPDATE_INCOMPATIBLE`) and the only way forward is
 * `adb uninstall com.guiforge.bati` — which takes the SQLite database, and therefore the
 * hero, the streak and the whole journal, with it. Testing a UI change should not cost a
 * training history.
 *
 * With the suffix, `npx expo run:android` installs `com.guiforge.bati.dev` as a second app with
 * its own sandbox: its own database (empty — expect to redo onboarding), its own notification
 * channels, its own widget. The release install is never touched.
 *
 * Each variant also names itself on the home screen — `Bati (dev)`, `Bati (perf)` — through a
 * `resValue`, which lands in a generated source set that outranks the `app_name` prebuild wrote
 * into `src/main/res`. Three identical launcher icons under three identical labels is how the
 * wrong app gets measured. The colour half of the same job is `withAndroidDebugIcon` for debug
 * (a `src/debug/res` override, amber) and the `iconBackground` resValue below for the local
 * release (cyan) — that one cannot be a source-set file, because `src/release/res` would repaint
 * the published app too.
 *
 * **Debug is suffixed always, release only when asked** (see below). The *published* release id
 * must stay exactly `com.guiforge.bati` or every already-installed copy — GitHub Releases, the
 * F-Droid repo — stops seeing updates as updates. That is the one thing this plugin must never
 * break, which is why the release suffix is opt-in through a property nothing in CI passes.
 *
 * Every app installed this way registers the `bati://` scheme, so Android asks which one to open
 * for a deep link.
 *
 * `android/` is committed for F-Droid's subdir check but regenerated by prebuild, so this has to
 * be a plugin rather than an edit; same reason as `withAndroidReleaseSigning` and
 * `withAndroidLintExtraTranslation`.
 */
const DEBUG_BLOCK = `        debug {
            signingConfig signingConfigs.debug
        }
`;

const SUFFIXED_DEBUG_BLOCK = `        debug {
            signingConfig signingConfigs.debug
            // See plugins/withAndroidLocalAppId.js — keeps the release install alive.
            applicationIdSuffix '.dev'
            resValue "string", "app_name", "Bati (dev)"
        }
`;

/**
 * The release build type gets the same protection, but only on demand: a release build is also
 * how the app is measured, and measuring it in dev is worthless — the dev bundle is several
 * times heavier and Hermes does not run under the same conditions. Without a suffix that
 * measurement has to install over the real app, and if no release key is on the machine the
 * build is debug-signed, Android refuses the update, and the tempting fix takes the database.
 *
 * `npm run android:release` passes `-PbatiLocalId=.perf`. Nothing in CI or in the F-Droid recipe
 * passes it, so the published id stays exactly `com.guiforge.bati`.
 */
const RELEASE_MINIFY = `            minifyEnabled enableMinifyInReleaseBuilds
`;

const SUFFIXED_RELEASE_MINIFY = `            // See plugins/withAndroidLocalAppId.js — set by npm run android:release, never by CI.
            if (project.hasProperty('batiLocalId')) {
                applicationIdSuffix batiLocalId
                resValue "string", "app_name", "Bati (" + batiLocalId.substring(1) + ")"
                resValue "color", "iconBackground", "#06B6D4"
            }
            minifyEnabled enableMinifyInReleaseBuilds
`;

module.exports = function withAndroidLocalAppId(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withAndroidLocalAppId: expected a groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    if (!cfg.modResults.contents.includes("applicationIdSuffix '.dev'")) {
      if (!cfg.modResults.contents.includes(DEBUG_BLOCK)) {
        throw new Error("withAndroidLocalAppId: debug build type is not the shape expected");
      }
      cfg.modResults.contents = cfg.modResults.contents.replace(DEBUG_BLOCK, SUFFIXED_DEBUG_BLOCK);
    }

    if (!cfg.modResults.contents.includes("batiLocalId")) {
      if (!cfg.modResults.contents.includes(RELEASE_MINIFY)) {
        throw new Error("withAndroidLocalAppId: release build type is not the shape expected");
      }
      cfg.modResults.contents = cfg.modResults.contents.replace(
        RELEASE_MINIFY,
        SUFFIXED_RELEASE_MINIFY,
      );
    }

    return cfg;
  });
};
