const fs = require("node:fs");
const path = require("node:path");
const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins");

/**
 * What Android's own backup (Google's Auto Backup, Seedvault, a phone-to-phone transfer) carries.
 *
 * `allowBackup` has always been true here, with no rules, so everything under `files/` went —
 * database included, which is what makes a new phone come back with its hero at no cost to anyone.
 * These rules keep that and say it out loud, because two things changed:
 *
 * - `expo-secure-store` ships its own rules, and they are an *allow-list* of shared preferences:
 *   adopted as-is they would have backed up nothing but preferences and silently dropped the
 *   database. It is configured with `configureAndroidBackup: false` in app.json, and this file is
 *   the only one that writes backup rules.
 * - SecureStore now holds the key that encrypts backups (src/backupVault.ts). A Keystore-wrapped
 *   value cannot be decrypted on another device anyway, and restoring it would leave a key that
 *   throws on first read — so it is excluded, and the new phone asks for the password once.
 *
 * The database is included with its `-wal` and `-shm`: a full-data backup stops the app first, so
 * the three files are consistent with each other.
 *
 * `__tests__/android-backup-rules.test.ts` reads the committed output.
 */
/**
 * The live database and its journal, by name, and nothing else in `SQLite/`. That directory also
 * holds what backup and sync leave while they work: an import decrypted before the swap, another
 * device's history opened for comparison, the pre-restore `.bak`, snapshots waiting for the share
 * sheet. Some are plaintext the hero asked to have sealed, all count against the 25 MB quota past
 * which Android backs up nothing at all. Naming the three files keeps every one of those out
 * without a list of exclusions to forget the next one from.
 *
 * The name follows `SCHEMA_VERSION`, read from db/schemaVersion.ts so the two cannot drift.
 */
const schemaVersion = /SCHEMA_VERSION\s*=\s*(\d+)/.exec(
  fs.readFileSync(path.join(__dirname, "..", "db", "schemaVersion.ts"), "utf8"),
)?.[1];
if (!schemaVersion)
  throw new Error("withAndroidBackupRules: no SCHEMA_VERSION in db/schemaVersion.ts");
const DB = `SQLite/bati.v${schemaVersion}.db`;

const RULES = [
  `<include domain="file" path="${DB}"/>`,
  `<include domain="file" path="${DB}-wal"/>`,
  `<include domain="file" path="${DB}-shm"/>`,
  // SecureStore's file, named for what it is: the includes above already leave it out, and this
  // says so where the next reader looks.
  '<exclude domain="sharedpref" path="SecureStore.xml"/>',
];

const indent = (spaces) => RULES.map((rule) => " ".repeat(spaces) + rule).join("\n");

const FULL_BACKUP = `<?xml version="1.0" encoding="utf-8"?>
<!-- Android 11 and lower. Generated by plugins/withAndroidBackupRules.js. -->
<full-backup-content>
${indent(2)}
</full-backup-content>
`;

const EXTRACTION = `<?xml version="1.0" encoding="utf-8"?>
<!-- Android 12 and higher. Generated by plugins/withAndroidBackupRules.js. -->
<data-extraction-rules>
  <cloud-backup>
${indent(4)}
  </cloud-backup>
  <device-transfer>
${indent(4)}
  </device-transfer>
</data-extraction-rules>
`;

module.exports = function withAndroidBackupRules(config) {
  const withFiles = withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "app/src/main/res/xml");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "bati_backup_rules.xml"), FULL_BACKUP);
      fs.writeFileSync(path.join(dir, "bati_data_extraction_rules.xml"), EXTRACTION);
      return cfg;
    },
  ]);

  return withAndroidManifest(withFiles, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) throw new Error("withAndroidBackupRules: no <application> in the manifest");
    app.$["android:allowBackup"] = "true";
    app.$["android:fullBackupContent"] = "@xml/bati_backup_rules";
    app.$["android:dataExtractionRules"] = "@xml/bati_data_extraction_rules";
    return cfg;
  });
};
