const { withProjectBuildGradle } = require("@expo/config-plugins");

/**
 * Strip the GNU build-id from every native library, so two builds of the same source produce
 * byte-identical `.so` files.
 *
 * This is the last thing standing between this app and a **reproducible build** — the arrangement
 * where F-Droid compiles the source itself, compares the result against our signed APK, and on a
 * match publishes *ours*. That matters because without it F-Droid signs with its own key, and
 * nobody who installed from our repository or from GitHub can ever update across to the catalogue
 * listing without uninstalling first and losing their database. F-Droid's own template warns that
 * the choice is permanent: decline reproducible builds and the APK is signed with their key, and
 * you cannot enable it later.
 *
 * The measurement that led here: comparing our released APK against one built by `fdroid build`,
 * every `.so` differed by **exactly 20 bytes out of ~1.8 MB**, at offset 0x2d0 — the SHA-1 in
 * `.note.gnu.build-id`. Everything else, including the NDK version note, was already identical.
 * The compilation is deterministic; only the linker's identity stamp is not, because it hashes
 * intermediate objects whose paths differ between build roots.
 *
 * `--build-id=none` removes the note rather than trying to make it stable. Nothing on Android
 * consumes it — it exists for matching a binary to its debug symbols, and these are stripped
 * anyway.
 *
 * It has to be a `subprojects` block: the flag must reach every autolinked native module
 * (expo-sqlite, reanimated, react-native-screens and the rest), not just `:app`. Applied through
 * `com.android.library` and `com.android.application` so it lands on both, and appended to
 * `arguments` rather than assigned, so a module that already passes CMake arguments keeps them.
 *
 * `android/` is gitignored and regenerated by prebuild, so this has to be a plugin rather than an
 * edit; same reason as the other three under `plugins/`.
 */
const BLOCK = `
// See plugins/withAndroidReproducibleNative.js — makes .so files byte-identical across builds.
subprojects { subproject ->
  ["com.android.library", "com.android.application"].each { pluginId ->
    subproject.plugins.withId(pluginId) {
      subproject.android {
        defaultConfig {
          externalNativeBuild {
            cmake {
              arguments += "-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--build-id=none"
            }
            ndkBuild {
              arguments += "APP_LDFLAGS=-Wl,--build-id=none"
            }
          }
        }
      }
    }
  }
}
`;

module.exports = function withAndroidReproducibleNative(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withAndroidReproducibleNative: expected a groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    if (cfg.modResults.contents.includes("--build-id=none")) {
      return cfg;
    }
    cfg.modResults.contents += BLOCK;
    return cfg;
  });
};
