const { withGradleProperties } = require("@expo/config-plugins");

/**
 * Give Gradle enough memory to build every Expo module from source.
 *
 * `package.json` sets `expo.autolinking.buildFromSource`, so Gradle compiles **and lints** 42
 * subprojects instead of consuming 22 prebuilt AARs. Expo's generated default —
 * `-Xmx2048m -XX:MaxMetaspaceSize=512m` — was sized for the prebuilt case. With everything built
 * from source, `lintVitalAnalyzeRelease` loads far more classes than that leaves room for, and the
 * release build dies with `java.lang.OutOfMemoryError: Metaspace` on three modules at once.
 *
 * Metaspace holds class metadata, not objects, so the heap number is not what was short: raising
 * `-Xmx` alone would not have helped. Both are raised anyway because linting 42 modules wants the
 * heap too, and a GitHub runner has far more than this to give.
 *
 * The failure is worth recognising because it does not look like an out-of-memory problem from the
 * outside — Gradle reports three unrelated `lintVitalAnalyzeRelease` task failures, and the actual
 * cause is one line further down the log.
 *
 * `android/` is gitignored and regenerated by prebuild, so this has to be a plugin rather than an
 * edit; same reason as `withAndroidReleaseSigning` and `withAndroidLintExtraTranslation`.
 */
const JVM_ARGS = "-Xmx4096m -XX:MaxMetaspaceSize=1536m";

module.exports = function withAndroidGradleMemory(config) {
  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === "org.gradle.jvmargs",
    );

    if (!existing) {
      throw new Error(
        "withAndroidGradleMemory: org.gradle.jvmargs is not in the generated gradle.properties",
      );
    }
    existing.value = JVM_ARGS;
    return cfg;
  });
};
