const { withAppBuildGradle } = require("expo/config-plugins");

/**
 * Let a release build sign with a real key instead of Expo's debug one.
 *
 * The template Expo generates has exactly one signing config — `debug` — and points
 * `buildTypes.release` straight at it, with a comment telling you to fix that in production.
 * Nothing reads `MYAPP_UPLOAD_*` properties, so a CI job that writes them into
 * `gradle.properties` and calls `assembleRelease` produces a **debug-signed APK and reports
 * success**. That is the failure worth guarding against: not a build that breaks, but one that
 * quietly ships the wrong signature, which Android then refuses to update over.
 *
 * The signing config is conditional so a plain `expo run:android --variant release` still works
 * on a machine with no key — it falls back to debug exactly as before.
 *
 * `android/` is gitignored and regenerated by prebuild, so this has to be a plugin rather than an
 * edit; the same reason `withAndroidLintExtraTranslation` exists.
 */
const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withAndroidReleaseSigning: expected a groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    if (cfg.modResults.contents.includes("MYAPP_UPLOAD_STORE_FILE")) {
      return cfg;
    }

    // Add the config next to `debug`, inside the existing signingConfigs block.
    const debugBlockEnd = `            keyPassword 'android'
        }
`;
    if (!cfg.modResults.contents.includes(debugBlockEnd)) {
      throw new Error("withAndroidReleaseSigning: could not find the debug signingConfig block");
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(
      debugBlockEnd,
      debugBlockEnd + RELEASE_SIGNING_CONFIG,
    );

    // Then point the release build type at it — only when a key was actually supplied.
    const releaseUsesDebug = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;
    if (!cfg.modResults.contents.includes(releaseUsesDebug)) {
      throw new Error("withAndroidReleaseSigning: release build type is not the shape expected");
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(
      releaseUsesDebug,
      `        release {
            // Signed with the release key when one is supplied (see plugins/withAndroidReleaseSigning.js),
            // and with the debug key otherwise so a local release build still works.
            signingConfig project.hasProperty('MYAPP_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
    );

    return cfg;
  });
};
