#!/usr/bin/env python3
"""Generate the session countdown beeps.

    python3 scripts/generate-sounds.py

Pure tones, written with the standard library's `wave`. That is the whole point: a sound
whose entire definition is a formula in this file has no licence question to answer, no sample
pack behind it and nothing for an F-Droid reviewer to chase. It also means the files can be
regenerated byte-for-byte from the repository, which is more than most assets here can say.

Deliberately unmusical. The last three seconds of a rest need to be *heard over a gym*, not
enjoyed; anything richer is a sound design project and this is a metronome.
"""

import math
import struct
import wave
from pathlib import Path

# 22.05 kHz is twice the highest partial these tones have. Doubling it doubles the file for
# frequencies that are not in the signal.
RATE = 22050
OUT = Path(__file__).resolve().parents[1] / "assets" / "sounds"

# A sine that starts and stops at a non-zero sample clicks — the discontinuity is broadband and
# louder than the tone. Five milliseconds of fade at each end is inaudible and removes it.
FADE_SECONDS = 0.005


def samples(freq: float, ms: int, gain: float) -> bytes:
    count = int(RATE * ms / 1000)
    fade = int(RATE * FADE_SECONDS)
    return b"".join(
        struct.pack(
            "<h",
            int(
                32767
                * gain
                * min(1.0, i / fade, (count - i) / fade)
                * math.sin(2 * math.pi * freq * i / RATE)
            ),
        )
        for i in range(count)
    )


def tone(path: Path, freq: float, ms: int, gain: float = 0.5) -> None:
    notes(path, [(freq, ms)], gain)


def notes(path: Path, parts: list[tuple[float, int]], gain: float = 0.5) -> None:
    """Tones back to back. A frequency of 0 is a silence of that length."""
    frames = b"".join(samples(freq, ms, gain) for freq, ms in parts)
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(RATE)
        out.writeframes(frames)
    print(f"{path.relative_to(Path(__file__).resolve().parents[1])}  {path.stat().st_size} bytes")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    # A short, dry tick for 3-2-1, and a longer one a fifth above it for the zero. The interval
    # is what carries "this one is different" when the phone is in a pocket.
    tone(OUT / "tick.wav", 880, 70)
    tone(OUT / "go.wav", 1320, 250)
    # Halfway through a per-side hold: change sides. Two short beeps at the zero's pitch, so it
    # reads as "not the end" against the single long one that does end the set.
    notes(OUT / "switch.wav", [(1320, 90), (0, 70), (1320, 90)])


if __name__ == "__main__":
    main()
