#!/usr/bin/env bash
# Format and lint the Kotlin, with a ktlint this repo pins itself.
#
#   scripts/ktlint.sh --format   # rewrite what can be rewritten (the git hook does this)
#   scripts/ktlint.sh            # check only, and fail on anything left
#
# Why a script and not a Gradle plugin: the two Kotlin files here live in an Expo module whose
# build is generated by `expo prebuild`, so a plugin would have to survive being regenerated on
# every machine and in every pipeline. A pinned jar answers to nobody. Same shape as the two other
# outside tools this repo uses: `actionlint` by docker tag in ci.yml, `license-checker` by npx
# version.
#
# The style itself is in `.editorconfig`, which is the only place ktlint reads it from. Two-space
# indent, because that is what `expo-module-gradle-plugin` scaffolds and what these files have
# always been; ktlint's own default is four, and left to itself it reports five hundred errors on
# code that is perfectly consistent.
set -euo pipefail

VERSION="1.8.0"
SHA256="a3fd620207d5c40da6ca789b95e7f823c54e854b7fade7f613e91096a3706d75"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/bati-ktlint"
BIN="$CACHE/ktlint-$VERSION"
SOURCES="modules/bati-location/android/**/*.kt"

if [ ! -x "$BIN" ]; then
  echo "ktlint $VERSION is not in the cache, fetching it once."
  mkdir -p "$CACHE"
  tmp="$(mktemp "$CACHE/ktlint.XXXXXX")"
  # A formatter that rewrites source is a formatter worth checksumming: this jar runs with the
  # same rights as the commit it is about to edit.
  curl -fsSL -o "$tmp" \
    "https://github.com/ktlint/ktlint/releases/download/$VERSION/ktlint"
  actual="$(sha256sum "$tmp" | cut -d' ' -f1)"
  if [ "$actual" != "$SHA256" ]; then
    rm -f "$tmp"
    echo "ktlint checksum mismatch." >&2
    echo "  expected: $SHA256" >&2
    echo "  got:      $actual" >&2
    exit 1
  fi
  chmod +x "$tmp"
  mv "$tmp" "$BIN"
fi

# ktlint globs on its own, so the pattern is quoted rather than expanded by the shell: the hook
# passes staged paths, and without a pattern of our own an empty list would lint the whole tree.
exec "$BIN" "$@" "$SOURCES"
