#!/usr/bin/env python3
"""Write constants/villagerFaces.ts: where each villager's head and shoulders sit in its art.

The medallion beside a villager's line is 44 dp. The whole 3:4 figure shrinks to a smudge there,
so the medallion shows a square around the head instead, read from the image's alpha: the first
opaque row in the middle of the image is the top of the head, and the opaque run nearest the
middle just below it gives the head's centre. The square is 48 % of the image's width and starts a
little above the head.

Rerun after redrawing or adding a villager:  python3 scripts/villager-faces.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "assets/images/villagers"
OUT = ROOT / "constants/villagerFaces.ts"
SIDE = 0.48  # of the image width
LIFT = 0.06  # of the square, above the first opaque row
HEAD = 0.12  # of the image height, scanned below the top for the head's centre
# Only the middle of the image is searched: in the cheer pose both fists are raised above the
# head, on either side, and the first opaque row was a fist.
BAND = (0.4, 0.6)  # of the image width


def frame(path: Path) -> tuple[float, float, float]:
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    # Thresholded: the cutout leaves faint pixels in the background that are not the figure.
    alpha = im.getchannel("A").point(lambda a: 255 if a > 128 else 0)
    left, right = int(w * BAND[0]), int(w * BAND[1])
    bbox = alpha.crop((left, 0, right, h)).getbbox()
    assert bbox, f"{path.name} has no opaque pixel in its middle"
    top = bbox[1]
    # The head's centre: in each row just under the top, the opaque run nearest the middle, so a
    # forearm raised beside the head does not pull the centre towards it.
    centres = []
    for y in range(top + int(h * 0.02), min(h, top + int(h * HEAD))):
        runs, start = [], None
        for x in range(w + 1):
            on = x < w and alpha.getpixel((x, y)) > 0
            if on and start is None:
                start = x
            elif not on and start is not None:
                runs.append((start, x))
                start = None
        if runs:
            a, b = min(runs, key=lambda r: abs((r[0] + r[1]) / 2 - w / 2))
            centres.append((a + b) / 2)
    centres.sort()
    cx = centres[len(centres) // 2]
    side = w * SIDE
    x0 = min(max(0.0, cx - side / 2), w - side)
    y0 = max(0.0, top - side * LIFT)
    return round(x0 / w, 4), round(y0 / h, 4), SIDE


def main() -> None:
    rows: dict[str, dict[str, tuple[float, float, float]]] = {}
    for path in sorted(ART.glob("*.webp")):
        villager, pose = path.stem.rsplit("_", 1)
        rows.setdefault(villager, {})[pose] = frame(path)
    lines = [
        "// Generated by scripts/villager-faces.py from the villagers' alpha. Do not edit by hand.",
        'import type { VillagerId, VillagerPose } from "@/constants/villagers";',
        "",
        "/** The head-and-shoulders square in a villager's art, as fractions of its width and height. */",
        "export type FaceFrame = { x: number; y: number; side: number };",
        "",
        "export const VILLAGER_FACES: Record<VillagerId, Record<VillagerPose, FaceFrame>> = {",
    ]
    for villager, poses in rows.items():
        lines.append(f"  {villager}: {{")
        for pose, (x, y, side) in sorted(poses.items()):
            lines.append(f"    {pose}: {{ x: {x}, y: {y}, side: {side} }},")
        lines.append("  },")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {sum(len(p) for p in rows.values())} frames")


if __name__ == "__main__":
    main()
