import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * A hero's phone as the last release left it, opened by this build.
 *
 * `fixtures/backup/v2-phone-state.json` is the SecureStore and the preference items that v2.9's own
 * `backupCipher.ts` wrote (it was generated by running that file, byte for byte, not by this
 * build), and `v2-phone.batb` is a backup it sealed. An update changes the code and keeps the
 * phone: this is the test that says what survives. Everything a hero would notice is here: the
 * backups they made, the password, the recovery key, the device name sync knows them by.
 *
 * Frozen like the other fixtures. Regenerating it would mean writing it with newer code, which is
 * the one thing that makes it worthless.
 */
const FIXTURES = path.join(__dirname, "fixtures", "backup");
const state = JSON.parse(fs.readFileSync(path.join(FIXTURES, "v2-phone-state.json"), "utf8")) as {
  password: string;
  recovery: string;
  plaintext: string;
  file: string;
  secure: Record<string, string>;
  preferences: Record<string, string>;
};

const mockSecure = new Map<string, string>();
const mockPrefs = new Map<string, string>();

jest.mock("@/modules/bati-crypto", () => ({
  batiCrypto: () => require("./helpers/nodeBatiCrypto").nodeBatiCrypto,
}));
jest.mock("expo-secure-store", () => ({
  getItemAsync: (key: string) => Promise.resolve(mockSecure.get(key) ?? null),
  setItemAsync: (key: string, value: string) =>
    Promise.resolve().then(() => {
      mockSecure.set(key, value);
    }),
  deleteItemAsync: (key: string) =>
    Promise.resolve().then(() => {
      mockSecure.delete(key);
    }),
  canUseBiometricAuthentication: () => false,
}));
jest.mock("@/db/preferences", () => ({
  getPreference: (key: string) => Promise.resolve(mockPrefs.get(key) ?? null),
  setPreference: (key: string, value: string) =>
    Promise.resolve().then(() => {
      mockPrefs.set(key, value);
    }),
  deletePreference: (key: string) =>
    Promise.resolve().then(() => {
      mockPrefs.delete(key);
    }),
}));

import {
  changePassword,
  encryptionStatus,
  openBackup,
  sealBackup,
  vaultFormat,
} from "@/src/backupCipher";
import { entropyToWords } from "@/src/backupWords";
import { installId } from "@/src/installId";
import { nodeBatiCrypto } from "./helpers/nodeBatiCrypto";

const OLD_FILE = path.join(FIXTURES, state.file);
const LEGACY_ID = "0190a000-0000-7000-8000-00000000000a";
const b64 = (bytes: Uint8Array | Buffer) => Buffer.from(bytes).toString("base64");

let dir: string;
const at = (name: string) => path.join(dir, name);

/** The phone, as the update finds it. */
function updatedPhone() {
  mockSecure.clear();
  mockPrefs.clear();
  for (const [key, value] of Object.entries(state.secure)) mockSecure.set(key, value);
  for (const [key, value] of Object.entries(state.preferences)) mockPrefs.set(key, value);
}

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "bati-upgrade-"));
  fs.writeFileSync(at("plain.db"), "SQLite format 3\u0000 a session logged after the update");
  updatedPhone();
});

afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

const open = (file: string, out: string, secret?: string) =>
  openBackup(file, at(out), secret).then((o) => o.result);

/** A device on format 3 that this phone will meet: a tablet that updated first. */
async function updatedTablet() {
  const master = b64(Buffer.alloc(32, 11));
  const entropy = new Uint8Array(16).fill(7);
  const password = "a tablet password of fifteen+";
  const slots = [
    await nodeBatiCrypto.wrapSlot(master, b64(Buffer.from(password)), 3, 1, 19 * 1024, 2, 1),
    await nodeBatiCrypto.wrapSlot(master, b64(entropy), 4, 1, 0, 0, 0),
  ];
  await nodeBatiCrypto.sealFileV3(
    master,
    at("plain.db"),
    at("tablet.batb"),
    slots.map((s) => s.raw),
    "aabbccddeeff00112233445566778899",
    "9",
  );
  return { password, words: entropyToWords(entropy, "en").join(" ") };
}

describe("a phone updated from v2.9", () => {
  test("is still encrypted, still on format 2, and opens the backup it made before the update", async () => {
    expect(await encryptionStatus()).toBe("on");
    expect(await vaultFormat()).toBe(2);

    expect(await open(OLD_FILE, "out.db")).toBe("opened");
    expect(fs.readFileSync(at("out.db"), "utf8")).toBe(state.plaintext);
  });

  test("keeps the password and the recovery key it was given", async () => {
    mockSecure.clear(); // another phone, which knows nothing but what the hero remembers
    mockPrefs.clear();

    expect(await open(OLD_FILE, "a.db", state.password)).toBe("opened");
    expect(await open(OLD_FILE, "b.db", state.recovery)).toBe("opened");
    expect(await open(OLD_FILE, "c.db", state.recovery.replaceAll(" ", "").toUpperCase())).toBe(
      "opened",
    );
  });

  test("keeps writing backups that older builds and its own password open", async () => {
    await sealBackup(at("plain.db"), at("after.batb"));

    // Still format 2: the version byte after "BATB".
    expect(fs.readFileSync(at("after.batb")).subarray(0, 5)).toEqual(
      Buffer.from([0x42, 0x41, 0x54, 0x42, 2]),
    );
    mockSecure.clear();
    mockPrefs.clear();
    expect(await open(at("after.batb"), "out.db", state.password)).toBe("opened");
  });

  test("is still the same device to a sync server: its name does not change on update", async () => {
    expect(await installId()).toBe(LEGACY_ID);
    // And the name the previous build knew is left where it was, for a rollback.
    expect(mockSecure.get("bati.sync.install")).toBe(LEGACY_ID);
  });

  test("a password changed afterwards keeps the backups made before it", async () => {
    await changePassword("a brand new password, long enough", "en");

    expect(await open(OLD_FILE, "out.db")).toBe("opened");
    expect(fs.readFileSync(at("out.db"), "utf8")).toBe(state.plaintext);
  });

  test("a restore from Android's backup, where the keystore did not follow, is locked and writes nothing plain", async () => {
    mockSecure.clear();

    expect(await encryptionStatus()).toBe("locked");
    expect(await open(OLD_FILE, "out.db")).toBe("needsSecret");
  });
});

describe("then meeting a device that updated to format 3", () => {
  test("joins its vault, and everything this phone ever sealed still opens, with no question", async () => {
    const tablet = await updatedTablet();
    const outcome = await openBackup(at("tablet.batb"), at("t.db"), tablet.password);
    await outcome.join?.({ asPrimary: true });

    expect(await vaultFormat()).toBe(3);
    expect(await open(OLD_FILE, "old.db")).toBe("opened");
    expect(fs.readFileSync(at("old.db"), "utf8")).toBe(state.plaintext);
  });

  test("from then on it writes format 3, which the tablet opens with its own password and with its words", async () => {
    const tablet = await updatedTablet();
    const outcome = await openBackup(at("tablet.batb"), at("t.db"), tablet.password);
    await outcome.join?.({ asPrimary: true });
    await sealBackup(at("plain.db"), at("mine.batb"));

    expect(fs.readFileSync(at("mine.batb")).subarray(4, 5)).toEqual(Buffer.from([3]));
    mockSecure.clear();
    mockPrefs.clear();
    expect(await open(at("mine.batb"), "a.db", tablet.password)).toBe("opened");
    expect(await open(at("mine.batb"), "b.db", tablet.words)).toBe("opened");
  });

  test("its own v2.9 recovery key and password still open the v2.9 file on a fresh phone, after all of it", async () => {
    const tablet = await updatedTablet();
    const outcome = await openBackup(at("tablet.batb"), at("t.db"), tablet.password);
    await outcome.join?.({ asPrimary: true });

    mockSecure.clear();
    mockPrefs.clear();
    expect(await open(OLD_FILE, "x.db", state.recovery)).toBe("opened");
    expect(await open(OLD_FILE, "y.db", state.password)).toBe("opened");
  });
});
