# Maestro Configuration
# https://maestro.mobile.dev/

flows:
  - app-launch.yaml
  - home-navigation.yaml
  - quest-gallery.yaml

# Default app ID
appId: com.anonymous.bati

# Screenshots output directory
screenshotsDir: ./screenshots
